version: '3.7'
services:
  db:
    image: postgres:latest
    container_name: iddatalogger_db
    restart: always
    environment:
      POSTGRES_USER: iddatalogger
      POSTGRES_DB: vwid
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - persistent_data_db:/var/lib/postgresql/data:rw

  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile-app
    container_name: iddatalogger_app
    environment:
      IDDATALOGGER_USERNAME: ${IDDATALOGGER_USERNAME}
      IDDATALOGGER_PASSWORD: ${IDDATALOGGER_PASSWORD}
      IDDATALOGGER_VIN: ${IDDATALOGGER_VIN}
      IDDATALOGGER_BASE_UPDATERATE: ${IDDATALOGGER_BASE_UPDATERATE}
      IDDATALOGGER_INCREASED_UPDATERATE: ${IDDATALOGGER_INCREASED_UPDATERATE}
      IDDATALOGGER_CARPIC_VIEWDIRECTION: ${IDDATALOGGER_CARPIC_VIEWDIRECTION}
      IDDATALOGGER_CARPIC_ANGLE: ${IDDATALOGGER_CARPIC_ANGLE}
      IDDATALOGGER_CARPIC_FLIP: ${IDDATALOGGER_CARPIC_FLIP}
      IDDATALOGGER_TIMEZONE: ${IDDATALOGGER_TIMEZONE}
      IDDATALOGGER_LOGGING_DEBUG_ENABLE: ${IDDATALOGGER_LOGGING_DEBUG_ENABLE}
      IDDATALOGGER_LOGGING_FILE_ENABLE: ${IDDATALOGGER_LOGGING_FILE_ENABLE}
      IDDATALOGGER_DB_HOST: iddatalogger_db
      IDDATALOGGER_DB_DBNAME: vwid
      IDDATALOGGER_DB_USER: iddatalogger
      IDDATALOGGER_IDVIEW_USERNAME: ${IDDATALOGGER_IDVIEW_USERNAME}
      IDDATALOGGER_IDVIEW_PASSWORD: ${IDDATALOGGER_IDVIEW_PASSWORD}
      IDDATALOGGER_API_KEY: ${IDDATALOGGER_API_KEY}
    depends_on:
      - db
    restart: always
    volumes:
      - persistent_data_app:/usr/src/IDDataLogger/data:rw

  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile-web
    container_name: iddatalogger_web
    environment:
      DB_HOST: iddatalogger_db
      DB_NAME: vwid
      DB_USER: iddatalogger
      FORCE_ALLOW_HTTP: "true"
    restart: always
    ports:
      - "${IDDATALOGGER_WEB_PORT}:80"

volumes:
  persistent_data_db:
  persistent_data_app: